name: Build and Release APK
on:
  push:
    tags:
      - '*'  # Trigger su qualsiasi tag
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.6
          
      - run: flutter pub get

      - name: Create .env file
        run: |
          echo "# Environment variables for production build" > .env
          echo "DISCOGS_TOKEN=${{ secrets.DISCOGS_TOKEN }}" >> .env
      - name: Verify .env file
        run: |
          echo "Verifying .env file exists and has content:"
          ls -la .env
          echo "File content (without sensitive data):"
          grep -v "API_KEY\|DATABASE_URL" .env || true

      - run: flutter build apk
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Release automatica generata da workflow
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
